In [1]:
from sac.agent_pytorch import SAC_Agent_Torch

Using TensorFlow backend.


In [2]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

from envs.gym_car_intersect_fixed import CarRacingHackatonContinuousFixed

successfully register gym env 'CarIntersect-v5'


In [3]:
env = CarRacingHackatonContinuousFixed()
s = env.reset()
s = np.rollaxis(s, 2, 0)  

count of car images: 57
count of track count: 11
background image shape: [540.8 304. ]
play field shape: [62.26315789 35.        ]


In [4]:
s, _, _, _ = env.step([-0.1, 1.0, 0])
s = np.rollaxis(s, 2, 0)

In [5]:
s.shape

(3, 304, 541)

In [6]:
agent = SAC_Agent_Torch(s.shape, 4,  128)

In [7]:
agent.get_batch_actions(np.array([s, s]), )

torch.Size([2, 4])
torch.Size([2, 4])


ValueError: too many values to unpack (expected 2)

In [8]:
agent.get_single_action(s, need_argmax=True, use_gumbel=False)

2

In [9]:
agent._Policy.evaluate_gumbel(
        torch.tensor(np.array([s / 256, s / 2], dtype=np.float32)), 
        temperature=10
    )

torch.Size([2, 4])
torch.Size([2, 4])


(tensor([[0., 1., 0., 0.],
         [1., 0., 0., 0.]], grad_fn=<AddBackward0>),
 tensor([[0.2508, 0.2403, 0.2625, 0.2464],
         [0.2586, 0.1939, 0.3444, 0.2031]], grad_fn=<SoftmaxBackward>),
 tensor([[0.2403, 0.2508],
         [0.1939, 0.2586]], grad_fn=<IndexBackward>))

In [18]:
a / a.sum()

array([0.0982, 0.2012, 0.6006, 0.1   ])